esphome:
  name: capteurlumiere

esp8266:
  board: nodemcuv2

# Enable Home Assistant API
api:
  password: !secret high_password

ota:
  password: !secret high_password

captive_portal:
web_server:
  port: 80
  js_include: "./v2/www.js"
  js_url: ""
  version: 2

wifi:
  networks:
    - ssid: !secret wifi_ssid1
      password: !secret low_password
    - ssid: !secret wifi_ssid2
      password: !secret low_password
    - ssid: !secret wifi_ssid3
      password: !secret low_password
    - ssid: !secret wifi_ssid4
      password: !secret low_password
  manual_ip:
    static_ip: 192.168.1.84
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  ap:
    ssid: "Alarme Fallback Hotspot"
    password: "!secret low_password"