esphome:
  name: capteurlumiere
  # Ce bloc ordonne à l'ESP de s'endormir dès que les données sont envoyées
  on_boot:
    priority: -10
    then:
      - delay: 30s # Laisse 10s pour se connecter au Wi-Fi et envoyer les mesures
      - deep_sleep.enter: deep_sleep_1

esp8266:
  board: nodemcuv2

# Configuration du bus I2C
i2c:
  sda: D1
  scl: D2
  scan: true

# Mode Sommeil Profond (1 minute)
deep_sleep:
  id: deep_sleep_1
  sleep_duration: 60s

api:
  password: !secret high_password

ota:
  password: !secret high_password

wifi:
  networks:
    - ssid: !secret wifi_exterieur
      password: !secret low_password
  manual_ip:
    static_ip: !secret ip
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  fast_connect: true # Crucial pour économiser la batterie
  ap:
    ssid: "Alarme Fallback Hotspot"
    password: !secret low_password

sensor:
  - platform: bh1750
    name: "light"
    address: 0x23
    update_interval: 1s # On mesure une seule fois au démarrage
    unit_of_measurement: lx

  - platform: adc
    pin: A0
    name: "battery"
    update_interval: 1s # On mesure une seule fois au démarrage
    unit_of_measurement: "V"
    filters:
      - multiply: 10.2
    icon: "mdi:battery"